### ISSUE TITLE
obj/key.o

### ISSUE THREAD

**Issue by mohaxars** [SimplicityDev2018/Simplicity#1]

**Comment by SimplicityDev2018** [comment]
Make Sure you have Secp256k1 on your system before compiling.

Linux (terminal)

cd Simplicity/src/secp256k1
chmod +x autogen.sh
sudo ./autogen.sh
sudo ./configure
sudo make && make install


Windows (msys)

cd /c/PATH-TO-SRC-CODE/Simplicity/src/secp256k1
./autogen.sh
./configure
make && make install

Issue Closed.
